apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: spark-fsharp-from-prebuilt
  namespace: spark-jobs
spec:
  type: Scala
  mode: cluster
  image: "spark-on-k8s-dotnet:v2.4.3-from-prebuilt"
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.deploy.dotnet.DotnetRunner
  mainApplicationFile: "local:///opt/spark/jars/microsoft-spark-2.4.x-0.4.0.jar"
  arguments:
    - "dotnet"
    - "Microsoft.Spark.FSharp.Examples.dll"
    - "Sql.Basic"
    - "/opt/spark/examples/src/main/resources/people.json"
  sparkVersion: "2.4.3"
  restartPolicy:
    type: Never
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.4.3
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.3
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.12.0.jar"
      port: 8090
